### ISSUE TITLE
Issue with connection with 10.0.0.1 

### ISSUE THREAD

**Issue by ResearchIntern98** [wladwm/ban2bgp#1]
Hi,
We were trying to run ban2bgp!
On doing  cargo run  only  this  gets  printed:
Listening on http://0.0.0.0:8080
A process  to port 179 also opens!
But Connecting to 10.0.0.1:179 does not print?
We made point to point to a route with ubuntu machine keeping ip addresses as mentioned!

Earlier we had  to  change tokio-util = "0.6.6" to tokio-util = { version = "0.6.6",  features = ["full"] }  to  overcome  build error  in Cargo.toml

**Comment by wladwm** [comment]
Hi.

It should connect to your BGP router specified in ban2bgp.ini as peers=10.0.0.1 AS65535
Listen port was specified as listen=0.0.0.0:1179 - port 1179, not 179! Because you can not listen at port below 1024 if you're not root.

**Comment by ResearchIntern98** [comment]
With or without  sudo with 1179  or  179,  it is not connecting to 10.0.0.1

**Comment by wladwm** [comment]
Could you please show your ban2bgp.ini ?
I will try to test

**Comment by ResearchIntern98** [comment]
[main]
httplisten=0.0.0.0:8080
listen=0.0.0.0:1179
nexthop=198.18.0.1
communities=666:666
peers=10.0.0.1 AS65535
duration=3600
skiplist=10.0.0.0/24

**Comment by wladwm** [comment]
Could you please replace content by following and try again?

[main]
httplisten=0.0.0.0:8080
listen=0.0.0.0:1179
nexthop=198.18.0.1
communities=666:666
peers=peer_r1
duration=3600
skiplist=10.0.0.0/24

[peer_r1]
peer=10.0.0.1
as=65535
mode=blackhole

**Comment by ResearchIntern98** [comment]
Doing this change in ban2bgp.ini solved the issue!
Advertised routes are added, but not getting removed after duration defined! Why?

**Comment by wladwm** [comment]
Please update ban2bgp and rebuild.
When routes should expire please check on main page (http://...:8080) presence of these routes.

**Comment by wladwm** [comment]
Seems that problem was solved any way...
