### ISSUE TITLE
Stopping the Router from forwarding the IP info

### ISSUE THREAD

**Issue by atulbunkar** [wladwm/ban2bgp#2]
Hello, I have executed your code Ban2BGP. 
I have established neighbourhood between my system and Router. 
When I am pushing IPs( to block ) from my system to the router , I don't want it to forward the information ahead to other routers.  How do we stop that from happening or is it already taken care of ?

**Comment by wladwm** [comment]
Hello.

If you want to customize route distribution policy you should set it on the router.
For example, if you dont want received announces propagate to ebgp peers - you can set well-known no-export community on incoming announces.
By default, routes will not propagate between ibgp peers (ibgp split-horizont rule).

**Comment by atulbunkar** [comment]
Thanks for the reply. I found that instead of no-export community option , the no-advertise was the better choice in our case.

**Comment by wladwm** [comment]
Supposed that blackhole routes should propagate to entire AS to stop evil traffic on every router.
Or, if you have routers with flowspec support, firewall traffic on AS border.
But sure you can use it as you wish :-)
