### ISSUE TITLE
Is eBGP possible with this?

### ISSUE THREAD

**Issue by ship51** [wladwm/ban2bgp#3]
Hi, I ran this code and was able to establish iBGP with my router, however I wish to setup eBGP.
How do I do this?

**Comment by wladwm** [comment]
Hi. 
It's not AS number, it's buffer size.
Suppose that you will use ibgp. What's the problem? You should specify asn in peer ini section:
[peer_r1]
peer=10.0.0.1
as=65535
mode=blackhole

as - it's AS number.

**Comment by ship51** [comment]
yeah, I figured, thank you

**Comment by ship51** [comment]
Hi, I am trying to provision an IP from my pc to the router in ebgp mode and it is suggesting me "invalid or currupt AS path".
How do I set the AS path attribute, which is empty (as seen from Wireshark dump), is it possible to add this from the ban2bgp.ini configuration file?

> Nov  1 15:42:14: %BGP_SESSION-5-ADJCHANGE: neighbor 10.1.1.1 IPv4 Unicast topology base removed from session  BGP Notification sent
Nov  1 15:42:24: %BGP-5-ADJCHANGE: neighbor 10.1.1.1 Up 
Nov  1 15:42:24: %BGP-5-ADJCHANGE: neighbor 10.1.1.1 Down BGP Notification sent
Nov  1 15:42:24: %BGP-3-NOTIFICATION: sent to neighbor 10.1.1.1 3/11 (invalid or corrupt AS path) 4 bytes 50020000 
Nov  1 15:42:24: BGP: 10.1.1.1 Bad attributes
Nov  1 15:42:24: %BGP-4-MSGDUMP: unsupported or mal-formatted message received from 10.1.1.1: 
FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0039 0200 0000 1D40 0101 0250 0200 0040 
0504 0000 000A C008 0402 9A02 9A40 0304 0A01 0101 200C 0101 01

**Comment by ship51** [comment]
I see this is possible by changing the line

https://github.com/wladwm/ban2bgp/blob/4dcd0e752c984de51a562a2550e5bbccc7be503b/src/bgppeer.rs#L85

However, I dont see the updates on my router, any fix for that? Wireshark shows the data being sent is fine.

**Comment by ship51** [comment]
Wireshark:

Path attributes
    Path Attribute - ORIGIN: INCOMPLETE
    Path Attribute - AS_PATH: 65535 33771 
    Path Attribute - LOCAL_PREF: 10
    Path Attribute - COMMUNITIES: 666:666 
    Path Attribute - NEXT_HOP: 198.18.0.1

**Comment by wladwm** [comment]
Hello.
This software supposed to use only as iBGP. I can't imagine reason to use it with eBGP.
To support eBGP it need to little upgrade.
Could you please give me some more information about your case?

**Comment by ship51** [comment]
Hi, the use case I want to test is as follows:
I wish to connect to the router in eBGP mode and be able to push routes to it via the API defined. Rest of the functionality remains the same.

It would be really helpful if you could suggest necessary changes to be make so as to use this in eBGP mode. Any suggestions on how to go about it (from a development perspective) would also be great!

**Comment by wladwm** [comment]
It't not exactly what I mean, but anyway ...
Please update repo from github, now you can set localas in peer section to specify local as for ban2bgp.

**Comment by atulbunkar** [comment]
Hello, We are trying to setup eBGP from your code, Neighborhood is created successfully but routes are not getting pushed. 
On wireshark we can see the update packet is sent from our system to the router but it does not get updated to the routing table. Can you tell us what could be the reason for this? Thanks.
